on: [push]
name: List the repository

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Ls on repository
        run: |
          pwd
          ls