on: [push]
name: Shell Commands

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Try JS Action
        uses: actions/hello-world-javascript-action@master
        with:
          who-to-great: Hugo
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"
      - name: Ls on repository
        run: ls -l